# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/auth.proto\x12\x1c\x63om.mimikko.app.api.idp.view\"\x85\x01\n\x0cLoginRequest\x12>\n\x0b\x61\x63\x63ountType\x18\x01 \x01(\x0e\x32).com.mimikko.app.api.idp.view.AccountType\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x12\n\nverifyCode\x18\x04 \x01(\t\")\n\x08response\x12\x0e\n\x06userId\x18\x01 \x01(\x03\x12\r\n\x05token\x18\x02 \x01(\t*h\n\x0b\x41\x63\x63ountType\x12\x18\n\x14\x41\x43\x43OUNT_TYPE_UNKNOWN\x10\x00\x12\t\n\x05PHONE\x10\x01\x12\t\n\x05\x45MAIL\x10\x02\x12\x0b\n\x07\x41\x43\x43OUNT\x10\x03\x12\x06\n\x02QQ\x10\x04\x12\x06\n\x02WX\x10\x05\x12\x0c\n\x08\x42ILIBILI\x10\x06\x32\x65\n\x04\x41uth\x12]\n\x05Login\x12*.com.mimikko.app.api.idp.view.LoginRequest\x1a&.com.mimikko.app.api.idp.view.response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACCOUNTTYPE._serialized_start=229
  _ACCOUNTTYPE._serialized_end=333
  _LOGINREQUEST._serialized_start=51
  _LOGINREQUEST._serialized_end=184
  _RESPONSE._serialized_start=186
  _RESPONSE._serialized_end=227
  _AUTH._serialized_start=335
  _AUTH._serialized_end=436
# @@protoc_insertion_point(module_scope)
