# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import character_pb2 as proto_dot_character__pb2


class CharacterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnergyExchange = channel.unary_unary(
                '/com.mimikko.app.api.general.character.Character/EnergyExchange',
                request_serializer=proto_dot_character__pb2.EnergyExchangeRequest.SerializeToString,
                response_deserializer=proto_dot_character__pb2.response.FromString,
                )
        self.ListCharacter = channel.unary_unary(
                '/com.mimikko.app.api.general.character.Character/ListCharacter',
                request_serializer=proto_dot_character__pb2.ListCharacterRequest.SerializeToString,
                response_deserializer=proto_dot_character__pb2.response2.FromString,
                )
        self.CharacterLevelManualUpgrade = channel.unary_unary(
                '/com.mimikko.app.api.general.character.Character/CharacterLevelManualUpgrade',
                request_serializer=proto_dot_character__pb2.CharacterLevelManualUpgradeRequest.SerializeToString,
                response_deserializer=proto_dot_character__pb2.EMPTY.FromString,
                )
        self.ListCharacterLevelReward = channel.unary_unary(
                '/com.mimikko.app.api.general.character.Character/ListCharacterLevelReward',
                request_serializer=proto_dot_character__pb2.ListCharacterLevelRewardRequest.SerializeToString,
                response_deserializer=proto_dot_character__pb2.response4.FromString,
                )
        self.ReceiveCharacterLevelReward = channel.unary_unary(
                '/com.mimikko.app.api.general.character.Character/ReceiveCharacterLevelReward',
                request_serializer=proto_dot_character__pb2.ReceiveCharacterLevelRewardRequest.SerializeToString,
                response_deserializer=proto_dot_character__pb2.EMPTY.FromString,
                )


class CharacterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnergyExchange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCharacter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CharacterLevelManualUpgrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCharacterLevelReward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveCharacterLevelReward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CharacterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnergyExchange': grpc.unary_unary_rpc_method_handler(
                    servicer.EnergyExchange,
                    request_deserializer=proto_dot_character__pb2.EnergyExchangeRequest.FromString,
                    response_serializer=proto_dot_character__pb2.response.SerializeToString,
            ),
            'ListCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCharacter,
                    request_deserializer=proto_dot_character__pb2.ListCharacterRequest.FromString,
                    response_serializer=proto_dot_character__pb2.response2.SerializeToString,
            ),
            'CharacterLevelManualUpgrade': grpc.unary_unary_rpc_method_handler(
                    servicer.CharacterLevelManualUpgrade,
                    request_deserializer=proto_dot_character__pb2.CharacterLevelManualUpgradeRequest.FromString,
                    response_serializer=proto_dot_character__pb2.EMPTY.SerializeToString,
            ),
            'ListCharacterLevelReward': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCharacterLevelReward,
                    request_deserializer=proto_dot_character__pb2.ListCharacterLevelRewardRequest.FromString,
                    response_serializer=proto_dot_character__pb2.response4.SerializeToString,
            ),
            'ReceiveCharacterLevelReward': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveCharacterLevelReward,
                    request_deserializer=proto_dot_character__pb2.ReceiveCharacterLevelRewardRequest.FromString,
                    response_serializer=proto_dot_character__pb2.EMPTY.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.mimikko.app.api.general.character.Character', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Character(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnergyExchange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.general.character.Character/EnergyExchange',
            proto_dot_character__pb2.EnergyExchangeRequest.SerializeToString,
            proto_dot_character__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.general.character.Character/ListCharacter',
            proto_dot_character__pb2.ListCharacterRequest.SerializeToString,
            proto_dot_character__pb2.response2.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CharacterLevelManualUpgrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.general.character.Character/CharacterLevelManualUpgrade',
            proto_dot_character__pb2.CharacterLevelManualUpgradeRequest.SerializeToString,
            proto_dot_character__pb2.EMPTY.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCharacterLevelReward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.general.character.Character/ListCharacterLevelReward',
            proto_dot_character__pb2.ListCharacterLevelRewardRequest.SerializeToString,
            proto_dot_character__pb2.response4.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveCharacterLevelReward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.general.character.Character/ReceiveCharacterLevelReward',
            proto_dot_character__pb2.ReceiveCharacterLevelRewardRequest.SerializeToString,
            proto_dot_character__pb2.EMPTY.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
