# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import mail_pb2 as proto_dot_mail__pb2


class MailStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListMail = channel.unary_unary(
                '/com.mimikko.app.api.general.mail.Mail/ListMail',
                request_serializer=proto_dot_mail__pb2.request.SerializeToString,
                response_deserializer=proto_dot_mail__pb2.response.FromString,
                )
        self.GetMail = channel.unary_unary(
                '/com.mimikko.app.api.general.mail.Mail/GetMail',
                request_serializer=proto_dot_mail__pb2.request2.SerializeToString,
                response_deserializer=proto_dot_mail__pb2.response2.FromString,
                )
        self.ReceiveAllMailAttachment = channel.unary_unary(
                '/com.mimikko.app.api.general.mail.Mail/ReceiveAllMailAttachment',
                request_serializer=proto_dot_mail__pb2.request3.SerializeToString,
                response_deserializer=proto_dot_mail__pb2.response3.FromString,
                )


class MailServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListMail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveAllMailAttachment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MailServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListMail': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMail,
                    request_deserializer=proto_dot_mail__pb2.request.FromString,
                    response_serializer=proto_dot_mail__pb2.response.SerializeToString,
            ),
            'GetMail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMail,
                    request_deserializer=proto_dot_mail__pb2.request2.FromString,
                    response_serializer=proto_dot_mail__pb2.response2.SerializeToString,
            ),
            'ReceiveAllMailAttachment': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveAllMailAttachment,
                    request_deserializer=proto_dot_mail__pb2.request3.FromString,
                    response_serializer=proto_dot_mail__pb2.response3.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.mimikko.app.api.general.mail.Mail', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Mail(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListMail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.general.mail.Mail/ListMail',
            proto_dot_mail__pb2.request.SerializeToString,
            proto_dot_mail__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.general.mail.Mail/GetMail',
            proto_dot_mail__pb2.request2.SerializeToString,
            proto_dot_mail__pb2.response2.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveAllMailAttachment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.general.mail.Mail/ReceiveAllMailAttachment',
            proto_dot_mail__pb2.request3.SerializeToString,
            proto_dot_mail__pb2.response3.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
