# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/material.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/material.proto\x12$com.mimikko.app.api.general.material\"r\n\nStatistics\x12\x10\n\x08typeCode\x18\x01 \x01(\t\x12\x10\n\x08typeName\x18\x02 \x01(\t\x12\x10\n\x08maxValue\x18\x03 \x01(\x05\x12\r\n\x05value\x18\x04 \x01(\x05\x12\x0b\n\x03url\x18\x05 \x01(\t\x12\x12\n\nattributes\x18\x06 \x01(\t\"\xbf\x02\n\x10GetMaterialReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x63over\x18\x03 \x01(\t\x12\r\n\x05level\x18\x04 \x01(\t\x12\r\n\x05isOwn\x18\x05 \x01(\x08\x12\x0f\n\x07summary\x18\x06 \x01(\t\x12\x44\n\nattributes\x18\x07 \x03(\x0b\x32\x30.com.mimikko.app.api.general.material.Attributes\x12\x44\n\nstatistics\x18\x08 \x01(\x0b\x32\x30.com.mimikko.app.api.general.material.Statistics\x12\x45\n\x04\x66ile\x18\t \x01(\x0b\x32\x37.com.mimikko.app.api.general.material.MaterialFileReply\"(\n\nAttributes\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"C\n\x11MaterialFileReply\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x10\n\x08\x63hecksum\x18\x03 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.material_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATISTICS._serialized_start=62
  _STATISTICS._serialized_end=176
  _GETMATERIALREPLY._serialized_start=179
  _GETMATERIALREPLY._serialized_end=498
  _ATTRIBUTES._serialized_start=500
  _ATTRIBUTES._serialized_end=540
  _MATERIALFILEREPLY._serialized_start=542
  _MATERIALFILEREPLY._serialized_end=609
# @@protoc_insertion_point(module_scope)
