# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import material_pb2 as proto_dot_material__pb2


class MaterialStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListMaterial = channel.unary_unary(
                '/com.mimikko.app.api.general.material.Material/ListMaterial',
                request_serializer=proto_dot_material__pb2.ListMaterialRequest.SerializeToString,
                response_deserializer=proto_dot_material__pb2.response.FromString,
                )


class MaterialServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListMaterial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MaterialServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListMaterial': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMaterial,
                    request_deserializer=proto_dot_material__pb2.ListMaterialRequest.FromString,
                    response_serializer=proto_dot_material__pb2.response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.mimikko.app.api.general.material.Material', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Material(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListMaterial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.general.material.Material/ListMaterial',
            proto_dot_material__pb2.ListMaterialRequest.SerializeToString,
            proto_dot_material__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
