# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/param.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/param.proto\x12\x1e\x63om.mimikko.app.api.play.param\"\xbd\x01\n\x19MaterialScalarDetailReply\x12\x14\n\x0cmaterialCode\x18\x01 \x01(\t\x12\x12\n\nscalarCode\x18\x04 \x01(\t\x12\x12\n\nscalarName\x18\x05 \x01(\t\x12\x13\n\x0bscalarCover\x18\x06 \x01(\t\x12\r\n\x05value\x18\x08 \x01(\x02\x12>\n\nattributes\x18\t \x03(\x0b\x32*.com.mimikko.app.api.play.param.Attributes\"\x99\x02\n\x12PlayCharacterReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\x05\x12\x0e\n\x06\x61vatar\x18\x04 \x01(\t\x12>\n\nstatistics\x18\x05 \x03(\x0b\x32*.com.mimikko.app.api.play.param.Statistics\x12\x42\n\x08packages\x18\x06 \x01(\x0b\x32\x30.com.mimikko.app.api.play.param.PackageTypeReply\x12\x44\n\nattributes\x18\x07 \x03(\x0b\x32\x30.com.mimikko.app.api.play.param.AttributesString\".\n\x10\x41ttributesString\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"w\n\nAttributes\x12>\n\x02m1\x18\x01 \x03(\x0b\x32\x32.com.mimikko.app.api.play.param.Attributes.M1Entry\x1a)\n\x07M1Entry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\\\n\x10PackageTypeReply\x12\x39\n\x04type\x18\x01 \x01(\x0e\x32+.com.mimikko.app.api.play.param.PackageType\x12\r\n\x05\x63odes\x18\x02 \x03(\t\"\x9e\x01\n\nStatistics\x12\x10\n\x08typeCode\x18\x01 \x01(\t\x12\x10\n\x08typeName\x18\x02 \x01(\t\x12\x10\n\x08maxValue\x18\x03 \x01(\x05\x12\r\n\x05value\x18\x04 \x01(\x05\x12\x0b\n\x03url\x18\x05 \x01(\t\x12>\n\nattributes\x18\x06 \x03(\x0b\x32*.com.mimikko.app.api.play.param.Attributes*)\n\x0bPackageType\x12\t\n\x05MODEL\x10\x00\x12\x06\n\x02\x41I\x10\x01\x12\x07\n\x03\x45XP\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.param_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ATTRIBUTES_M1ENTRY._options = None
  _ATTRIBUTES_M1ENTRY._serialized_options = b'8\001'
  _PACKAGETYPE._serialized_start=953
  _PACKAGETYPE._serialized_end=994
  _MATERIALSCALARDETAILREPLY._serialized_start=54
  _MATERIALSCALARDETAILREPLY._serialized_end=243
  _PLAYCHARACTERREPLY._serialized_start=246
  _PLAYCHARACTERREPLY._serialized_end=527
  _ATTRIBUTESSTRING._serialized_start=529
  _ATTRIBUTESSTRING._serialized_end=575
  _ATTRIBUTES._serialized_start=577
  _ATTRIBUTES._serialized_end=696
  _ATTRIBUTES_M1ENTRY._serialized_start=655
  _ATTRIBUTES_M1ENTRY._serialized_end=696
  _PACKAGETYPEREPLY._serialized_start=698
  _PACKAGETYPEREPLY._serialized_end=790
  _STATISTICS._serialized_start=793
  _STATISTICS._serialized_end=951
# @@protoc_insertion_point(module_scope)
