# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/scalar.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/scalar.proto\x12\"com.mimikko.app.api.general.scalar\"\x17\n\x07request\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\x90\x01\n\x08response\x12\x14\n\x0cmaterialCode\x18\x01 \x01(\t\x12\x12\n\nscalarCode\x18\x02 \x01(\t\x12\x10\n\x08oldValue\x18\x03 \x01(\x01\x12\x10\n\x08newValue\x18\x04 \x01(\x01\x12\x12\n\nscalarType\x18\x05 \x01(\x05\x12\x10\n\x08maxValue\x18\x06 \x01(\x02\x12\x10\n\x08minValue\x18\x07 \x01(\x02\"\xba\x01\n\tresponse2\x12\x13\n\x0bunknownData\x18\x01 \x01(\x03\x12\x0e\n\x06userId\x18\x02 \x01(\x03\x12\x0f\n\x07string2\x18\x03 \x01(\t\x12\x0f\n\x07string4\x18\x04 \x01(\t\x12\x14\n\x0cmaterialCode\x18\x05 \x01(\t\x12\x0e\n\x06int326\x18\x06 \x01(\x05\x12\x14\n\x0c\x65nergryValue\x18\x07 \x01(\x05\x12\x17\n\x0fmaxEnergryValue\x18\x0e \x01(\x05\x12\x11\n\timagePath\x18\x13 \x01(\t2\xe9\x01\n\x06Scalar\x12p\n\x11GetUserAutoScalar\x12+.com.mimikko.app.api.general.scalar.request\x1a,.com.mimikko.app.api.general.scalar.response\"\x00\x12m\n\rGetUserScalar\x12+.com.mimikko.app.api.general.scalar.request\x1a-.com.mimikko.app.api.general.scalar.response2\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.scalar_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=58
  _REQUEST._serialized_end=81
  _RESPONSE._serialized_start=84
  _RESPONSE._serialized_end=228
  _RESPONSE2._serialized_start=231
  _RESPONSE2._serialized_end=417
  _SCALAR._serialized_start=420
  _SCALAR._serialized_end=653
# @@protoc_insertion_point(module_scope)
