# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import scalar_pb2 as proto_dot_scalar__pb2


class ScalarStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserAutoScalar = channel.unary_unary(
                '/com.mimikko.app.api.general.scalar.Scalar/GetUserAutoScalar',
                request_serializer=proto_dot_scalar__pb2.GetUserAutoScalarRequest.SerializeToString,
                response_deserializer=proto_dot_scalar__pb2.response.FromString,
                )
        self.GetUserScalar = channel.unary_unary(
                '/com.mimikko.app.api.general.scalar.Scalar/GetUserScalar',
                request_serializer=proto_dot_scalar__pb2.GetUserScalarRequest.SerializeToString,
                response_deserializer=proto_dot_scalar__pb2.response2.FromString,
                )
        self.ListCoinExchangeRelation = channel.unary_unary(
                '/com.mimikko.app.api.general.scalar.Scalar/ListCoinExchangeRelation',
                request_serializer=proto_dot_scalar__pb2.ListCoinExchangeRelationRequest.SerializeToString,
                response_deserializer=proto_dot_scalar__pb2.response3.FromString,
                )
        self.Exchange = channel.unary_unary(
                '/com.mimikko.app.api.general.scalar.Scalar/Exchange',
                request_serializer=proto_dot_scalar__pb2.ExchangeRequest.SerializeToString,
                response_deserializer=proto_dot_scalar__pb2.response4.FromString,
                )


class ScalarServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserAutoScalar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserScalar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCoinExchangeRelation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exchange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScalarServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserAutoScalar': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserAutoScalar,
                    request_deserializer=proto_dot_scalar__pb2.GetUserAutoScalarRequest.FromString,
                    response_serializer=proto_dot_scalar__pb2.response.SerializeToString,
            ),
            'GetUserScalar': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserScalar,
                    request_deserializer=proto_dot_scalar__pb2.GetUserScalarRequest.FromString,
                    response_serializer=proto_dot_scalar__pb2.response2.SerializeToString,
            ),
            'ListCoinExchangeRelation': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCoinExchangeRelation,
                    request_deserializer=proto_dot_scalar__pb2.ListCoinExchangeRelationRequest.FromString,
                    response_serializer=proto_dot_scalar__pb2.response3.SerializeToString,
            ),
            'Exchange': grpc.unary_unary_rpc_method_handler(
                    servicer.Exchange,
                    request_deserializer=proto_dot_scalar__pb2.ExchangeRequest.FromString,
                    response_serializer=proto_dot_scalar__pb2.response4.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.mimikko.app.api.general.scalar.Scalar', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Scalar(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserAutoScalar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.general.scalar.Scalar/GetUserAutoScalar',
            proto_dot_scalar__pb2.GetUserAutoScalarRequest.SerializeToString,
            proto_dot_scalar__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserScalar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.general.scalar.Scalar/GetUserScalar',
            proto_dot_scalar__pb2.GetUserScalarRequest.SerializeToString,
            proto_dot_scalar__pb2.response2.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCoinExchangeRelation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.general.scalar.Scalar/ListCoinExchangeRelation',
            proto_dot_scalar__pb2.ListCoinExchangeRelationRequest.SerializeToString,
            proto_dot_scalar__pb2.response3.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Exchange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.general.scalar.Scalar/Exchange',
            proto_dot_scalar__pb2.ExchangeRequest.SerializeToString,
            proto_dot_scalar__pb2.response4.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
