# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import sign_pb2 as proto_dot_sign__pb2


class SignStub(object):
    """定义服务,用在rpc传输中
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserSignStatus = channel.unary_unary(
                '/com.mimikko.app.api.general.sign.Sign/GetUserSignStatus',
                request_serializer=proto_dot_sign__pb2.GetUserSignStatusRequest.SerializeToString,
                response_deserializer=proto_dot_sign__pb2.response.FromString,
                )
        self.Sign = channel.unary_unary(
                '/com.mimikko.app.api.general.sign.Sign/Sign',
                request_serializer=proto_dot_sign__pb2.SignRequest.SerializeToString,
                response_deserializer=proto_dot_sign__pb2.response2.FromString,
                )


class SignServicer(object):
    """定义服务,用在rpc传输中
    """

    def GetUserSignStatus(self, request, context):
        """获得签到天数
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sign(self, request, context):
        """签到
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserSignStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserSignStatus,
                    request_deserializer=proto_dot_sign__pb2.GetUserSignStatusRequest.FromString,
                    response_serializer=proto_dot_sign__pb2.response.SerializeToString,
            ),
            'Sign': grpc.unary_unary_rpc_method_handler(
                    servicer.Sign,
                    request_deserializer=proto_dot_sign__pb2.SignRequest.FromString,
                    response_serializer=proto_dot_sign__pb2.response2.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.mimikko.app.api.general.sign.Sign', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Sign(object):
    """定义服务,用在rpc传输中
    """

    @staticmethod
    def GetUserSignStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.general.sign.Sign/GetUserSignStatus',
            proto_dot_sign__pb2.GetUserSignStatusRequest.SerializeToString,
            proto_dot_sign__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Sign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.general.sign.Sign/Sign',
            proto_dot_sign__pb2.SignRequest.SerializeToString,
            proto_dot_sign__pb2.response2.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
