# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import signin_pb2 as proto_dot_signin__pb2


class SignInStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SignInDetail = channel.unary_unary(
                '/com.mimikko.app.api.daylife.activity.SignIn/SignInDetail',
                request_serializer=proto_dot_signin__pb2.SignInDetailRequest.SerializeToString,
                response_deserializer=proto_dot_signin__pb2.SignInDetailResponse.FromString,
                )
        self.SignIn = channel.unary_unary(
                '/com.mimikko.app.api.daylife.activity.SignIn/SignIn',
                request_serializer=proto_dot_signin__pb2.SignInRequest.SerializeToString,
                response_deserializer=proto_dot_signin__pb2.SignInResponse.FromString,
                )


class SignInServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SignInDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignInServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SignInDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.SignInDetail,
                    request_deserializer=proto_dot_signin__pb2.SignInDetailRequest.FromString,
                    response_serializer=proto_dot_signin__pb2.SignInDetailResponse.SerializeToString,
            ),
            'SignIn': grpc.unary_unary_rpc_method_handler(
                    servicer.SignIn,
                    request_deserializer=proto_dot_signin__pb2.SignInRequest.FromString,
                    response_serializer=proto_dot_signin__pb2.SignInResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.mimikko.app.api.daylife.activity.SignIn', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SignIn(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SignInDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.daylife.activity.SignIn/SignInDetail',
            proto_dot_signin__pb2.SignInDetailRequest.SerializeToString,
            proto_dot_signin__pb2.SignInDetailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SignIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.daylife.activity.SignIn/SignIn',
            proto_dot_signin__pb2.SignInRequest.SerializeToString,
            proto_dot_signin__pb2.SignInResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
