# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/signin.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/signin.proto\x12$com.mimikko.app.api.daylife.activity\"[\n\x13SignInDetailRequest\x12\x12\n\nactivityId\x18\x01 \x01(\x03\x12\x10\n\x08\x65ndpoint\x18\x02 \x01(\t\x12\x0c\n\x04page\x18\x03 \x01(\x05\x12\x10\n\x08pageSize\x18\x04 \x01(\x05\"\x8a\x01\n\x14SignInDetailResponse\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08pageSize\x18\x02 \x01(\x05\x12\r\n\x05total\x18\x03 \x01(\x03\x12\x43\n\x08\x63ontents\x18\x04 \x03(\x0b\x32\x31.com.mimikko.app.api.daylife.activity.RewardReply\"e\n\x0bRewardReply\x12\x0f\n\x07isToday\x18\x01 \x01(\x08\x12\x0e\n\x06signed\x18\x02 \x01(\x08\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\r\n\x05\x63over\x18\x05 \x01(\t\x12\x0b\n\x03num\x18\x06 \x01(\x05\"5\n\rSignInRequest\x12\x12\n\nactivityId\x18\x01 \x01(\x03\x12\x10\n\x08\x65ndpoint\x18\x02 \x01(\t\"f\n\x0eSignInResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x43\n\x08\x63ontents\x18\x02 \x03(\x0b\x32\x31.com.mimikko.app.api.daylife.activity.RewardReply2\x89\x02\n\x06SignIn\x12\x87\x01\n\x0cSignInDetail\x12\x39.com.mimikko.app.api.daylife.activity.SignInDetailRequest\x1a:.com.mimikko.app.api.daylife.activity.SignInDetailResponse\"\x00\x12u\n\x06SignIn\x12\x33.com.mimikko.app.api.daylife.activity.SignInRequest\x1a\x34.com.mimikko.app.api.daylife.activity.SignInResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.signin_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIGNINDETAILREQUEST._serialized_start=60
  _SIGNINDETAILREQUEST._serialized_end=151
  _SIGNINDETAILRESPONSE._serialized_start=154
  _SIGNINDETAILRESPONSE._serialized_end=292
  _REWARDREPLY._serialized_start=294
  _REWARDREPLY._serialized_end=395
  _SIGNINREQUEST._serialized_start=397
  _SIGNINREQUEST._serialized_end=450
  _SIGNINRESPONSE._serialized_start=452
  _SIGNINRESPONSE._serialized_end=554
  _SIGNIN._serialized_start=557
  _SIGNIN._serialized_end=822
# @@protoc_insertion_point(module_scope)
