# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/store.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/store.proto\x12\x1e\x63om.mimikko.app.api.mall.store\"{\n\x1bGetProductPageByTagsRequest\x12\x10\n\x08typeCode\x18\x01 \x01(\t\x12\x0c\n\x04tags\x18\x02 \x03(\t\x12\x0c\n\x04page\x18\x03 \x01(\x05\x12\x10\n\x08pageSize\x18\x04 \x01(\x05\x12\x0c\n\x04isOr\x18\x05 \x01(\x05\x12\x0e\n\x06orders\x18\x06 \x03(\t\"\x8a\x01\n\x1cGetProductPageByTagsResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x10\n\x08pageSize\x18\x03 \x01(\x05\x12;\n\x07\x63ontent\x18\x04 \x03(\x0b\x32*.com.mimikko.app.api.mall.store.GoodsReply\"\xa9\x01\n\nGoodsReply\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05\x63over\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04\x63ode\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x01\x12\x15\n\rdiscountPrice\x18\x06 \x01(\x01\x12\x10\n\x08packaged\x18\x07 \x01(\x05\x12\x11\n\tlimitTime\x18\x08 \x01(\t\x12\x0c\n\x04tags\x18\t \x01(\t\x12\x0b\n\x03s10\x18\n \x01(\t\"\x14\n\x12ListTagSiftRequest\"Y\n\x13ListTagSiftResponse\x12\x42\n\rtagCategories\x18\x01 \x03(\x0b\x32+.com.mimikko.app.api.mall.store.TagCategory\"\x8c\x01\n\x0bTagCategory\x12\x14\n\x0c\x63\x61tegoriesId\x18\x01 \x01(\x05\x12\x16\n\x0e\x63\x61tegoriesName\x18\x02 \x01(\t\x12\x1c\n\x14\x63\x61tegoriesBackground\x18\x03 \x01(\t\x12\x31\n\x04tags\x18\x04 \x03(\x0b\x32#.com.mimikko.app.api.mall.store.Tag\"(\n\x03Tag\x12\x12\n\nbackground\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2\x97\x02\n\x05Store\x12\x93\x01\n\x14GetProductPageByTags\x12;.com.mimikko.app.api.mall.store.GetProductPageByTagsRequest\x1a<.com.mimikko.app.api.mall.store.GetProductPageByTagsResponse\"\x00\x12x\n\x0bListTagSift\x12\x32.com.mimikko.app.api.mall.store.ListTagSiftRequest\x1a\x33.com.mimikko.app.api.mall.store.ListTagSiftResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.store_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETPRODUCTPAGEBYTAGSREQUEST._serialized_start=53
  _GETPRODUCTPAGEBYTAGSREQUEST._serialized_end=176
  _GETPRODUCTPAGEBYTAGSRESPONSE._serialized_start=179
  _GETPRODUCTPAGEBYTAGSRESPONSE._serialized_end=317
  _GOODSREPLY._serialized_start=320
  _GOODSREPLY._serialized_end=489
  _LISTTAGSIFTREQUEST._serialized_start=491
  _LISTTAGSIFTREQUEST._serialized_end=511
  _LISTTAGSIFTRESPONSE._serialized_start=513
  _LISTTAGSIFTRESPONSE._serialized_end=602
  _TAGCATEGORY._serialized_start=605
  _TAGCATEGORY._serialized_end=745
  _TAG._serialized_start=747
  _TAG._serialized_end=787
  _STORE._serialized_start=790
  _STORE._serialized_end=1069
# @@protoc_insertion_point(module_scope)
