# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import store_pb2 as proto_dot_store__pb2


class StoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProductPageByTags = channel.unary_unary(
                '/com.mimikko.app.api.mall.store.Store/GetProductPageByTags',
                request_serializer=proto_dot_store__pb2.GetProductPageByTagsRequest.SerializeToString,
                response_deserializer=proto_dot_store__pb2.GetProductPageByTagsResponse.FromString,
                )
        self.ListTagSift = channel.unary_unary(
                '/com.mimikko.app.api.mall.store.Store/ListTagSift',
                request_serializer=proto_dot_store__pb2.ListTagSiftRequest.SerializeToString,
                response_deserializer=proto_dot_store__pb2.ListTagSiftResponse.FromString,
                )


class StoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProductPageByTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTagSift(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProductPageByTags': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductPageByTags,
                    request_deserializer=proto_dot_store__pb2.GetProductPageByTagsRequest.FromString,
                    response_serializer=proto_dot_store__pb2.GetProductPageByTagsResponse.SerializeToString,
            ),
            'ListTagSift': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTagSift,
                    request_deserializer=proto_dot_store__pb2.ListTagSiftRequest.FromString,
                    response_serializer=proto_dot_store__pb2.ListTagSiftResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.mimikko.app.api.mall.store.Store', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Store(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProductPageByTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.mall.store.Store/GetProductPageByTags',
            proto_dot_store__pb2.GetProductPageByTagsRequest.SerializeToString,
            proto_dot_store__pb2.GetProductPageByTagsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTagSift(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.mall.store.Store/ListTagSift',
            proto_dot_store__pb2.ListTagSiftRequest.SerializeToString,
            proto_dot_store__pb2.ListTagSiftResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
