# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import task_pb2 as proto_dot_task__pb2


class TaskStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTask = channel.unary_unary(
                '/com.mimikko.app.api.play.task.Task/ListTask',
                request_serializer=proto_dot_task__pb2.request.SerializeToString,
                response_deserializer=proto_dot_task__pb2.response.FromString,
                )
        self.GetTaskRecord = channel.unary_unary(
                '/com.mimikko.app.api.play.task.Task/GetTaskRecord',
                request_serializer=proto_dot_task__pb2.request2.SerializeToString,
                response_deserializer=proto_dot_task__pb2.response2.FromString,
                )
        self.ListTaskCharacter = channel.unary_unary(
                '/com.mimikko.app.api.play.task.Task/ListTaskCharacter',
                request_serializer=proto_dot_task__pb2.request3.SerializeToString,
                response_deserializer=proto_dot_task__pb2.response3.FromString,
                )
        self.ReceiveTaskReward = channel.unary_unary(
                '/com.mimikko.app.api.play.task.Task/ReceiveTaskReward',
                request_serializer=proto_dot_task__pb2.request4.SerializeToString,
                response_deserializer=proto_dot_task__pb2.response4.FromString,
                )
        self.PickTask = channel.unary_unary(
                '/com.mimikko.app.api.play.task.Task/PickTask',
                request_serializer=proto_dot_task__pb2.request5.SerializeToString,
                response_deserializer=proto_dot_task__pb2.response5.FromString,
                )


class TaskServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTaskCharacter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveTaskReward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PickTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTask,
                    request_deserializer=proto_dot_task__pb2.request.FromString,
                    response_serializer=proto_dot_task__pb2.response.SerializeToString,
            ),
            'GetTaskRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskRecord,
                    request_deserializer=proto_dot_task__pb2.request2.FromString,
                    response_serializer=proto_dot_task__pb2.response2.SerializeToString,
            ),
            'ListTaskCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTaskCharacter,
                    request_deserializer=proto_dot_task__pb2.request3.FromString,
                    response_serializer=proto_dot_task__pb2.response3.SerializeToString,
            ),
            'ReceiveTaskReward': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveTaskReward,
                    request_deserializer=proto_dot_task__pb2.request4.FromString,
                    response_serializer=proto_dot_task__pb2.response4.SerializeToString,
            ),
            'PickTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PickTask,
                    request_deserializer=proto_dot_task__pb2.request5.FromString,
                    response_serializer=proto_dot_task__pb2.response5.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.mimikko.app.api.play.task.Task', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Task(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.task.Task/ListTask',
            proto_dot_task__pb2.request.SerializeToString,
            proto_dot_task__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTaskRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.task.Task/GetTaskRecord',
            proto_dot_task__pb2.request2.SerializeToString,
            proto_dot_task__pb2.response2.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTaskCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.task.Task/ListTaskCharacter',
            proto_dot_task__pb2.request3.SerializeToString,
            proto_dot_task__pb2.response3.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveTaskReward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.task.Task/ReceiveTaskReward',
            proto_dot_task__pb2.request4.SerializeToString,
            proto_dot_task__pb2.response4.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PickTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.task.Task/PickTask',
            proto_dot_task__pb2.request5.SerializeToString,
            proto_dot_task__pb2.response5.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
