# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import travelv2_pb2 as proto_dot_travelv2__pb2


class TravelV2Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTravelRecord = channel.unary_unary(
                '/com.mimikko.app.api.play.travelV2.TravelV2/ListTravelRecord',
                request_serializer=proto_dot_travelv2__pb2.ListTravelRecordRequest.SerializeToString,
                response_deserializer=proto_dot_travelv2__pb2.ListTravelRecordResponse.FromString,
                )
        self.ListTravelArea = channel.unary_unary(
                '/com.mimikko.app.api.play.travelV2.TravelV2/ListTravelArea',
                request_serializer=proto_dot_travelv2__pb2.ListTravelAreaRequest.SerializeToString,
                response_deserializer=proto_dot_travelv2__pb2.ListTravelAreaResponse.FromString,
                )
        self.ListTravelGroup = channel.unary_unary(
                '/com.mimikko.app.api.play.travelV2.TravelV2/ListTravelGroup',
                request_serializer=proto_dot_travelv2__pb2.ListTravelGroupRequest.SerializeToString,
                response_deserializer=proto_dot_travelv2__pb2.ListTravelGroupResponse.FromString,
                )
        self.ListTravelGroupReward = channel.unary_unary(
                '/com.mimikko.app.api.play.travelV2.TravelV2/ListTravelGroupReward',
                request_serializer=proto_dot_travelv2__pb2.ListTravelGroupRewardRequest.SerializeToString,
                response_deserializer=proto_dot_travelv2__pb2.ListTravelRewardReply.FromString,
                )
        self.Travel = channel.unary_unary(
                '/com.mimikko.app.api.play.travelV2.TravelV2/Travel',
                request_serializer=proto_dot_travelv2__pb2.TravelRequest.SerializeToString,
                response_deserializer=proto_dot_travelv2__pb2.TravelResponse.FromString,
                )
        self.CalculateTravelConsume = channel.unary_unary(
                '/com.mimikko.app.api.play.travelV2.TravelV2/CalculateTravelConsume',
                request_serializer=proto_dot_travelv2__pb2.CalculateTravelConsumeRequest.SerializeToString,
                response_deserializer=proto_dot_travelv2__pb2.CalculateTravelConsumeResponse.FromString,
                )
        self.ListTravelsCharacter = channel.unary_unary(
                '/com.mimikko.app.api.play.travelV2.TravelV2/ListTravelsCharacter',
                request_serializer=proto_dot_travelv2__pb2.ListTravelsCharacterRequest.SerializeToString,
                response_deserializer=proto_dot_travelv2__pb2.ListTravelsCharacterResponse.FromString,
                )
        self.GetTravelGroup = channel.unary_unary(
                '/com.mimikko.app.api.play.travelV2.TravelV2/GetTravelGroup',
                request_serializer=proto_dot_travelv2__pb2.GetTravelGroupRequest.SerializeToString,
                response_deserializer=proto_dot_travelv2__pb2.GetTravelGroupResponse.FromString,
                )
        self.GetTravelRecord = channel.unary_unary(
                '/com.mimikko.app.api.play.travelV2.TravelV2/GetTravelRecord',
                request_serializer=proto_dot_travelv2__pb2.GetTravelRecordRequest.SerializeToString,
                response_deserializer=proto_dot_travelv2__pb2.GetTravelRecordResponse.FromString,
                )
        self.ReceiveTravelReward = channel.unary_unary(
                '/com.mimikko.app.api.play.travelV2.TravelV2/ReceiveTravelReward',
                request_serializer=proto_dot_travelv2__pb2.ReceiveTravelRewardRequest.SerializeToString,
                response_deserializer=proto_dot_travelv2__pb2.ReceiveTravelRewardResponse.FromString,
                )
        self.ExchangePostcard = channel.unary_unary(
                '/com.mimikko.app.api.play.travelV2.TravelV2/ExchangePostcard',
                request_serializer=proto_dot_travelv2__pb2.ExchangePostcardRequest.SerializeToString,
                response_deserializer=proto_dot_travelv2__pb2.ExchangePostcardResponse.FromString,
                )


class TravelV2Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListTravelRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTravelArea(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTravelGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTravelGroupReward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Travel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateTravelConsume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTravelsCharacter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTravelGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTravelRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveTravelReward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangePostcard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TravelV2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTravelRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTravelRecord,
                    request_deserializer=proto_dot_travelv2__pb2.ListTravelRecordRequest.FromString,
                    response_serializer=proto_dot_travelv2__pb2.ListTravelRecordResponse.SerializeToString,
            ),
            'ListTravelArea': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTravelArea,
                    request_deserializer=proto_dot_travelv2__pb2.ListTravelAreaRequest.FromString,
                    response_serializer=proto_dot_travelv2__pb2.ListTravelAreaResponse.SerializeToString,
            ),
            'ListTravelGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTravelGroup,
                    request_deserializer=proto_dot_travelv2__pb2.ListTravelGroupRequest.FromString,
                    response_serializer=proto_dot_travelv2__pb2.ListTravelGroupResponse.SerializeToString,
            ),
            'ListTravelGroupReward': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTravelGroupReward,
                    request_deserializer=proto_dot_travelv2__pb2.ListTravelGroupRewardRequest.FromString,
                    response_serializer=proto_dot_travelv2__pb2.ListTravelRewardReply.SerializeToString,
            ),
            'Travel': grpc.unary_unary_rpc_method_handler(
                    servicer.Travel,
                    request_deserializer=proto_dot_travelv2__pb2.TravelRequest.FromString,
                    response_serializer=proto_dot_travelv2__pb2.TravelResponse.SerializeToString,
            ),
            'CalculateTravelConsume': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateTravelConsume,
                    request_deserializer=proto_dot_travelv2__pb2.CalculateTravelConsumeRequest.FromString,
                    response_serializer=proto_dot_travelv2__pb2.CalculateTravelConsumeResponse.SerializeToString,
            ),
            'ListTravelsCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTravelsCharacter,
                    request_deserializer=proto_dot_travelv2__pb2.ListTravelsCharacterRequest.FromString,
                    response_serializer=proto_dot_travelv2__pb2.ListTravelsCharacterResponse.SerializeToString,
            ),
            'GetTravelGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTravelGroup,
                    request_deserializer=proto_dot_travelv2__pb2.GetTravelGroupRequest.FromString,
                    response_serializer=proto_dot_travelv2__pb2.GetTravelGroupResponse.SerializeToString,
            ),
            'GetTravelRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTravelRecord,
                    request_deserializer=proto_dot_travelv2__pb2.GetTravelRecordRequest.FromString,
                    response_serializer=proto_dot_travelv2__pb2.GetTravelRecordResponse.SerializeToString,
            ),
            'ReceiveTravelReward': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveTravelReward,
                    request_deserializer=proto_dot_travelv2__pb2.ReceiveTravelRewardRequest.FromString,
                    response_serializer=proto_dot_travelv2__pb2.ReceiveTravelRewardResponse.SerializeToString,
            ),
            'ExchangePostcard': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangePostcard,
                    request_deserializer=proto_dot_travelv2__pb2.ExchangePostcardRequest.FromString,
                    response_serializer=proto_dot_travelv2__pb2.ExchangePostcardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.mimikko.app.api.play.travelV2.TravelV2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TravelV2(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTravelRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.travelV2.TravelV2/ListTravelRecord',
            proto_dot_travelv2__pb2.ListTravelRecordRequest.SerializeToString,
            proto_dot_travelv2__pb2.ListTravelRecordResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTravelArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.travelV2.TravelV2/ListTravelArea',
            proto_dot_travelv2__pb2.ListTravelAreaRequest.SerializeToString,
            proto_dot_travelv2__pb2.ListTravelAreaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTravelGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.travelV2.TravelV2/ListTravelGroup',
            proto_dot_travelv2__pb2.ListTravelGroupRequest.SerializeToString,
            proto_dot_travelv2__pb2.ListTravelGroupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTravelGroupReward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.travelV2.TravelV2/ListTravelGroupReward',
            proto_dot_travelv2__pb2.ListTravelGroupRewardRequest.SerializeToString,
            proto_dot_travelv2__pb2.ListTravelRewardReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Travel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.travelV2.TravelV2/Travel',
            proto_dot_travelv2__pb2.TravelRequest.SerializeToString,
            proto_dot_travelv2__pb2.TravelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CalculateTravelConsume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.travelV2.TravelV2/CalculateTravelConsume',
            proto_dot_travelv2__pb2.CalculateTravelConsumeRequest.SerializeToString,
            proto_dot_travelv2__pb2.CalculateTravelConsumeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTravelsCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.travelV2.TravelV2/ListTravelsCharacter',
            proto_dot_travelv2__pb2.ListTravelsCharacterRequest.SerializeToString,
            proto_dot_travelv2__pb2.ListTravelsCharacterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTravelGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.travelV2.TravelV2/GetTravelGroup',
            proto_dot_travelv2__pb2.GetTravelGroupRequest.SerializeToString,
            proto_dot_travelv2__pb2.GetTravelGroupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTravelRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.travelV2.TravelV2/GetTravelRecord',
            proto_dot_travelv2__pb2.GetTravelRecordRequest.SerializeToString,
            proto_dot_travelv2__pb2.GetTravelRecordResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveTravelReward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.travelV2.TravelV2/ReceiveTravelReward',
            proto_dot_travelv2__pb2.ReceiveTravelRewardRequest.SerializeToString,
            proto_dot_travelv2__pb2.ReceiveTravelRewardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExchangePostcard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.travelV2.TravelV2/ExchangePostcard',
            proto_dot_travelv2__pb2.ExchangePostcardRequest.SerializeToString,
            proto_dot_travelv2__pb2.ExchangePostcardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
