# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wallpaper.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/wallpaper.proto\x12%com.mimikko.app.api.daylife.wallpaper\"5\n\x13GetAllAlbumsRequest\x12\x0c\n\x04page\x18\x03 \x01(\x05\x12\x10\n\x08pageSize\x18\x04 \x01(\x05\"\x89\x01\n\x14GetAllAlbumsResponse\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08pageSize\x18\x02 \x01(\x05\x12\r\n\x05total\x18\x03 \x01(\x05\x12\x42\n\x07\x63ontent\x18\x04 \x03(\x0b\x32\x31.com.mimikko.app.api.daylife.wallpaper.AlbumReply\"\x8c\x01\n\nAlbumReply\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x63over\x18\x03 \x01(\t\x12\x12\n\ncoverThumb\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x08 \x01(\t\x12\x0e\n\x06\x63licks\x18\t \x01(\x05\x12\x0c\n\x04leaf\x18\n \x01(\x08\"K\n\x1cGetWallpaperByAlbumIdRequest\x12\x0b\n\x03\x61id\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x10\n\x08pageSize\x18\x03 \x01(\x05\"\x96\x01\n\x1dGetWallpaperByAlbumIdResponse\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08pageSize\x18\x02 \x01(\x05\x12\r\n\x05total\x18\x03 \x01(\x05\x12\x46\n\x07\x63ontent\x18\x04 \x03(\x0b\x32\x35.com.mimikko.app.api.daylife.wallpaper.WallpaperReply\"\x9b\x01\n\x0eWallpaperReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08imageUrl\x18\x03 \x01(\t\x12\x14\n\x0cimagePreview\x18\x04 \x01(\t\x12\x12\n\nimageThumb\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x0e\n\x06\x61uthor\x18\t \x01(\t\x12\x0e\n\x06\x63licks\x18\n \x01(\x05\x32\xbe\x02\n\tWallpaper\x12\x89\x01\n\x0cGetAllAlbums\x12:.com.mimikko.app.api.daylife.wallpaper.GetAllAlbumsRequest\x1a;.com.mimikko.app.api.daylife.wallpaper.GetAllAlbumsResponse\"\x00\x12\xa4\x01\n\x15GetWallpaperByAlbumId\x12\x43.com.mimikko.app.api.daylife.wallpaper.GetWallpaperByAlbumIdRequest\x1a\x44.com.mimikko.app.api.daylife.wallpaper.GetWallpaperByAlbumIdResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.wallpaper_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETALLALBUMSREQUEST._serialized_start=64
  _GETALLALBUMSREQUEST._serialized_end=117
  _GETALLALBUMSRESPONSE._serialized_start=120
  _GETALLALBUMSRESPONSE._serialized_end=257
  _ALBUMREPLY._serialized_start=260
  _ALBUMREPLY._serialized_end=400
  _GETWALLPAPERBYALBUMIDREQUEST._serialized_start=402
  _GETWALLPAPERBYALBUMIDREQUEST._serialized_end=477
  _GETWALLPAPERBYALBUMIDRESPONSE._serialized_start=480
  _GETWALLPAPERBYALBUMIDRESPONSE._serialized_end=630
  _WALLPAPERREPLY._serialized_start=633
  _WALLPAPERREPLY._serialized_end=788
  _WALLPAPER._serialized_start=791
  _WALLPAPER._serialized_end=1109
# @@protoc_insertion_point(module_scope)
