# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import work_pb2 as proto_dot_work__pb2


class WorkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListOrdinaryWork = channel.unary_unary(
                '/com.mimikko.app.api.play.work.Work/ListOrdinaryWork',
                request_serializer=proto_dot_work__pb2.ListOrdinaryWorkRequest.SerializeToString,
                response_deserializer=proto_dot_work__pb2.response.FromString,
                )
        self.GetOrdinaryWorkRecord = channel.unary_unary(
                '/com.mimikko.app.api.play.work.Work/GetOrdinaryWorkRecord',
                request_serializer=proto_dot_work__pb2.GetOrdinaryWorkRecordRequest.SerializeToString,
                response_deserializer=proto_dot_work__pb2.response2.FromString,
                )
        self.ReceiveOrdinaryWorkReward = channel.unary_unary(
                '/com.mimikko.app.api.play.work.Work/ReceiveOrdinaryWorkReward',
                request_serializer=proto_dot_work__pb2.ReceiveOrdinaryWorkRewardRequest.SerializeToString,
                response_deserializer=proto_dot_work__pb2.response3.FromString,
                )
        self.ListWorksCharacter = channel.unary_unary(
                '/com.mimikko.app.api.play.work.Work/ListWorksCharacter',
                request_serializer=proto_dot_work__pb2.ListWorksCharacterRequest.SerializeToString,
                response_deserializer=proto_dot_work__pb2.response4.FromString,
                )
        self.PickOrdinaryWork = channel.unary_unary(
                '/com.mimikko.app.api.play.work.Work/PickOrdinaryWork',
                request_serializer=proto_dot_work__pb2.PickOrdinaryWorkRequest.SerializeToString,
                response_deserializer=proto_dot_work__pb2.response5.FromString,
                )
        self.Refresh = channel.unary_unary(
                '/com.mimikko.app.api.play.work.Work/Refresh',
                request_serializer=proto_dot_work__pb2.RefreshRequest.SerializeToString,
                response_deserializer=proto_dot_work__pb2.RefreshResponse.FromString,
                )


class WorkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListOrdinaryWork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrdinaryWorkRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveOrdinaryWorkReward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorksCharacter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PickOrdinaryWork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refresh(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListOrdinaryWork': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOrdinaryWork,
                    request_deserializer=proto_dot_work__pb2.ListOrdinaryWorkRequest.FromString,
                    response_serializer=proto_dot_work__pb2.response.SerializeToString,
            ),
            'GetOrdinaryWorkRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrdinaryWorkRecord,
                    request_deserializer=proto_dot_work__pb2.GetOrdinaryWorkRecordRequest.FromString,
                    response_serializer=proto_dot_work__pb2.response2.SerializeToString,
            ),
            'ReceiveOrdinaryWorkReward': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveOrdinaryWorkReward,
                    request_deserializer=proto_dot_work__pb2.ReceiveOrdinaryWorkRewardRequest.FromString,
                    response_serializer=proto_dot_work__pb2.response3.SerializeToString,
            ),
            'ListWorksCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorksCharacter,
                    request_deserializer=proto_dot_work__pb2.ListWorksCharacterRequest.FromString,
                    response_serializer=proto_dot_work__pb2.response4.SerializeToString,
            ),
            'PickOrdinaryWork': grpc.unary_unary_rpc_method_handler(
                    servicer.PickOrdinaryWork,
                    request_deserializer=proto_dot_work__pb2.PickOrdinaryWorkRequest.FromString,
                    response_serializer=proto_dot_work__pb2.response5.SerializeToString,
            ),
            'Refresh': grpc.unary_unary_rpc_method_handler(
                    servicer.Refresh,
                    request_deserializer=proto_dot_work__pb2.RefreshRequest.FromString,
                    response_serializer=proto_dot_work__pb2.RefreshResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.mimikko.app.api.play.work.Work', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Work(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListOrdinaryWork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.work.Work/ListOrdinaryWork',
            proto_dot_work__pb2.ListOrdinaryWorkRequest.SerializeToString,
            proto_dot_work__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrdinaryWorkRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.work.Work/GetOrdinaryWorkRecord',
            proto_dot_work__pb2.GetOrdinaryWorkRecordRequest.SerializeToString,
            proto_dot_work__pb2.response2.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveOrdinaryWorkReward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.work.Work/ReceiveOrdinaryWorkReward',
            proto_dot_work__pb2.ReceiveOrdinaryWorkRewardRequest.SerializeToString,
            proto_dot_work__pb2.response3.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListWorksCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.work.Work/ListWorksCharacter',
            proto_dot_work__pb2.ListWorksCharacterRequest.SerializeToString,
            proto_dot_work__pb2.response4.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PickOrdinaryWork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.work.Work/PickOrdinaryWork',
            proto_dot_work__pb2.PickOrdinaryWorkRequest.SerializeToString,
            proto_dot_work__pb2.response5.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Refresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mimikko.app.api.play.work.Work/Refresh',
            proto_dot_work__pb2.RefreshRequest.SerializeToString,
            proto_dot_work__pb2.RefreshResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
